name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Remove node_modules and package-lock
        run: |
          rm -rf node_modules
          rm -f package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Verify TypeScript config
        run: |
          echo "=== tsconfig.json ==="
          cat tsconfig.json
          echo "=== tsconfig.app.json ==="
          cat tsconfig.app.json
          echo "=== vite.config.ts ==="
          cat vite.config.ts

      - name: Check file structure
        run: |
          echo "=== src/lib directory ==="
          ls -la src/lib/
          echo "=== src/contexts directory ==="
          ls -la src/contexts/

      - name: Build project
        run: npm run build
        env:
          NODE_ENV: production
          CI: true

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_FIELD_0CB2DFA1E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"                 # Location of your source files (i.e. package.json)
          api_location: "api"               # If you have no API, leave it as "api" or remove this line
          output_location: "dist"           # Vite defaults to `dist` after build
          
  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_FIELD_0CB2DFA1E }}
          action: "close"
